#!/bin/sh

#Autostart
killall sxhkd; sxhkd & 
exec picom & #if needed, add "killall picom"
killall dunst; dunst &
killall nitrogen; nitrogen --restore &
#redshift -x && redshift -O 4000k &
xsetroot -cursor_name left_ptr &
killall polybar
$HOME/.config/polybar/launch.sh &
#polybar example &

#variable
alias bc='bspc config'
alias br='bspc rule'

#Workspaces
bspc monitor DisplayPort-0 -d web term game 4 5 6 7 8 9
bspc monitor DisplayPort-1 -d dis mus 3 4 5 6 7 8 9

#Others
bc border_width 0
bc window_gap 10
bc split_ratio 0.50
bc borderless_monocle true
bc gapless_monocle true
bc focus_follows_pointer true


#rules
br -a feh state=floating
br -a sxiv state=floating
#br -a mpv state=floating
br -a discord desktop="dis"
br -a steam desktop="game"
